# Generated by Django 4.2.2 on 2023-06-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos/%Y/')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_cynologist', models.IntegerField()),
                ('group_cynologist', models.IntegerField()),
                ('people_single', models.IntegerField()),
                ('group_single', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='photos/%Y/')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('dogs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.dogs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cynologyst', to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='dogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.user'),
        ),
    ]
